'use strict';
const $=id=>document.getElementById(id);
const state={data:null,refs:[],ready:false,plan:null,version:0,cuts:[],batch:0,pending:new Set(),active:-1,playToken:0};
const limits={feature:[1800,10800],short:[60,1800],clip:[6,180],'long-play':[1800,10800],'one-act':[120,1800],advert:[6,120],mix:[15,600]};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function sources(ids,node){for(const id of ids){const s=state.data.sources.find(s=>s.id===id);const a=el('a',s.citation.match(/^\[\d+\]/)[0]+' '+s.title,'source');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';node.append(a);}}
function save(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function invalidate(){state.version++;state.plan=null;$('download-plan').hidden=true;$('plan-status').textContent='';$('plan').disabled=!state.ready;$('outline').replaceChildren(el('h3','Ready for your next outline.'),el('p','Select a format, original seed and dialogue language. No commercial reference script is adapted.'));}
function collection(){const q=$('search').value.trim().toLowerCase();const rows=state.data.items.filter(i=>($('kind').value==='all'||i.kind===$('kind').value)&&($('era').value==='all'||i.era===$('era').value)&&($('language-filter').value==='all'||i.language.includes($('language-filter').value))&&[i.title,i.summary,i.credits].join(' ').toLowerCase().includes(q));$('collection').replaceChildren();$('count').textContent=`${rows.length} of ${state.data.items.length} starter cards`;$('empty').hidden=rows.length>0;
 for(const i of rows){const selected=state.refs.includes(i.id),c=el('article',undefined,'card'+(selected?' selected':''));c.append(el('span',`${i.kind} / ${i.language} / ${i.era}`,'meta'),el('h3',i.title),el('p',i.summary));if(i.credits)c.append(el('p',i.credits,'artist'));if(i.production_minutes)c.append(el('p',`${i.production_minutes} minutes in the cited production; not a universal runtime.`,'small'));sources(i.source_ids,c);c.append(el('p',i.rights==='CC_BY_3.0_with_attribution_and_project_exclusions'?'Open-film licence conditions apply; see source.':'Reference / proposal only · no media hosted','small'));const b=el('button',selected?'Remove reference −':'Add research reference +','text-button add');b.id='add-'+i.id;b.disabled=!selected&&state.refs.length>=8;b.setAttribute('aria-pressed',String(selected));b.onclick=()=>{state.refs=selected?state.refs.filter(x=>x!==i.id):[...state.refs,i.id];invalidate();collection();$('reference-count').textContent=state.refs.length;$('selected').textContent=state.refs.length?'Research context only: '+state.refs.map(id=>state.data.items.find(i=>i.id===id).title).join(' · '):'No references selected. You can still plan an original piece.';$(b.id)?.focus({preventScroll:true});};c.append(b);$('collection').append(c);}}
function formatChanged(){const f=state.data.formats.find(f=>f.id===$('format').value);$('duration').min=limits[f.id][0];$('duration').max=limits[f.id][1];$('duration').value=f.default_seconds;invalidate();}
async function plan(){if(!$('duration').reportValidity())return;invalidate();const version=state.version;$('plan').disabled=true;$('plan-status').textContent='Preparing a local production outline…';try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({experience:'film',item_ids:[...state.refs],format:$('format').value,language:$('dialogue-language').value,seed:$('seed').value,duration_seconds:$('duration').valueAsNumber})});const p=await r.json();if(version!==state.version)return;if(!r.ok)throw new Error(p.error||'Plan unavailable');state.plan=p;$('outline').replaceChildren(el('p','ORIGINAL OUTLINE · NOT A FINISHED PRODUCTION','eyebrow'),el('h3',p.original_seed.title),el('p',p.original_seed.premise),el('pre',p.sample_dialogue.join('\n')));$('outline').querySelector('pre').lang={Marathi:'mr',Hindi:'hi',English:'en'}[p.sample_dialogue_language];const list=el('ol');for(const b of p.beats)list.append(el('li',`${b.start_seconds}s · ${b.title} (${b.budget_seconds}s budget)`));const d=el('details');d.append(el('summary','Review gates'));const ul=el('ul');p.review_gates.forEach(g=>ul.append(el('li',g)));d.append(ul);$('outline').append(list,d);$('download-plan').hidden=false;$('plan-status').textContent='Local Vyomaraj → Jarvis outline ready. No AI call or media rendering.';}catch(e){if(version===state.version)$('plan-status').textContent=e.message;}finally{if(version===state.version)$('plan').disabled=!state.ready;}}
function stop(){state.playToken++;state.active=-1;const p=$('preview');p.onloadedmetadata=null;p.pause();}
function clear(){state.batch++;stop();const p=$('preview');p.removeAttribute('src');p.load();p.hidden=true;for(const c of state.cuts)URL.revokeObjectURL(c.url);for(const url of state.pending)URL.revokeObjectURL(url);state.pending.clear();state.cuts=[];$('files').value='';$('files').disabled=!$('permission').checked;$('media-status').textContent='No footage selected. Nothing will autoplay.';renderCuts();}
function validCuts(){return $('permission').checked&&state.cuts.length>0&&state.cuts.every(c=>Number.isFinite(c.in)&&Number.isFinite(c.out)&&c.in>=0&&c.out>c.in&&c.out<=c.duration);}
function cutButtons(){$('play-mix').disabled=$('export-edl').disabled=!validCuts();}
function renderCuts(){
 $('cuts').replaceChildren();state.cuts.forEach((c,index)=>{const row=el('div',undefined,'cut');row.append(el('h3',`${index+1}. ${c.name}`),el('p',`${c.duration.toFixed(3)} seconds · local file`,'small'));const trim=el('div',undefined,'trim');for(const [key,title] of [['in','In (seconds)'],['out','Out (seconds)']]){const label=el('label',title),input=el('input');input.type='number';input.min=0;input.max=c.duration;input.step='any';input.value=c[key];input.setAttribute('aria-label',`${title} clip ${index+1}`);input.oninput=()=>{stop();c[key]=input.valueAsNumber;cutButtons();$('media-status').textContent=validCuts()?'Trim updated. Preview or export the sequence.':'Every cut needs 0 ≤ in < out ≤ duration.';};label.append(input);trim.append(label);}row.append(trim);const buttons=el('div',undefined,'buttons');for(const [text,delta] of [['↑',-1],['↓',1]]){const b=el('button',text);b.setAttribute('aria-label',`Move clip ${index+1} ${delta<0?'up':'down'}`);b.disabled=index+delta<0||index+delta>=state.cuts.length;b.onclick=()=>{stop();const next=index+delta;[state.cuts[index],state.cuts[next]]=[state.cuts[next],state.cuts[index]];renderCuts();};buttons.append(b);}const remove=el('button','Remove');remove.setAttribute('aria-label',`Remove clip ${index+1}`);remove.onclick=()=>{stop();$('preview').removeAttribute('src');$('preview').load();$('preview').hidden=true;URL.revokeObjectURL(c.url);state.cuts.splice(index,1);renderCuts();};buttons.append(remove);row.append(buttons);$('cuts').append(row);});cutButtons();
}
function probe(url){return new Promise((resolve,reject)=>{const p=document.createElement('video');p.preload='metadata';let settled=false;const timer=setTimeout(()=>finish(new Error('Could not read a finite duration within 8 seconds.')),8000);function finish(error){if(settled)return;settled=true;clearTimeout(timer);const duration=p.duration;p.onloadedmetadata=p.onseeked=p.onerror=null;p.removeAttribute('src');p.load();error?reject(error):resolve(duration);}function check(){if(Number.isFinite(p.duration)&&p.duration>0)finish();}p.onerror=()=>finish(new Error('Unsupported or unreadable video file.'));p.onloadedmetadata=()=>{check();if(!settled)p.currentTime=1e10;};p.onseeked=check;p.src=url;p.load();});}
async function addFiles(){const files=[...$('files').files];$('files').value='';if(!$('permission').checked)return;stop();const batch=++state.batch;$('files').disabled=true;let rejected=[];try{for(const file of files){if(batch!==state.batch||!$('permission').checked)break;if(state.cuts.length>=6||!file.type.startsWith('video/')||file.size>100*1024*1024||state.cuts.reduce((n,c)=>n+c.size,0)+file.size>300*1024*1024){rejected.push(file.name+': type/size/count limit');continue;}const url=URL.createObjectURL(file);state.pending.add(url);try{const duration=await probe(url);if(batch!==state.batch||!$('permission').checked){URL.revokeObjectURL(url);break;}state.cuts.push({name:file.name,size:file.size,url,duration,in:0,out:duration});}catch(e){URL.revokeObjectURL(url);rejected.push(file.name+': '+e.message);}finally{state.pending.delete(url);}}}finally{if(batch===state.batch){$('files').disabled=!$('permission').checked;renderCuts();$('media-status').textContent=`${state.cuts.length} local clip(s) ready. No upload.`+(rejected.length?' Skipped: '+rejected.join('; '):'');}}}
function playAt(index,token){if(token!==state.playToken||!validCuts())return;const p=$('preview');if(index>=state.cuts.length){stop();$('media-status').textContent='Sequence preview complete. No movie file was rendered.';return;}state.active=-1;const c=state.cuts[index];p.hidden=false;p.onloadedmetadata=async()=>{if(token!==state.playToken||p.currentSrc!==c.url)return;p.currentTime=c.in;state.active=index;try{await p.play();}catch(e){if(token===state.playToken&&state.active===index){stop();$('media-status').textContent='Playback did not start. Check codec support and try Preview again.';}}};p.src=c.url;p.load();$('media-status').textContent=`Previewing ${index+1} / ${state.cuts.length}: ${c.name}`;}
function nextCut(){if(state.active<0)return;playAt(state.active+1,state.playToken);}
function exportEDL(){if(!validCuts())return;let position=0;const clips=state.cuts.map(c=>{const row={filename:c.name,in_seconds:c.in,out_seconds:c.out,timeline_start_seconds:position};position+=c.out-c.in;return row;});save({schema_version:1,type:'local_edit_decision_list',transition:'hard_cut',audio:'original_clip_audio_only',timing:'approximate_seconds_not_frame_accurate',total_seconds:position,clips,media_included:false,media_uploaded:false,rights_acknowledgement:true,rights_verified:false,encoded_export:false},'vyomaraj-local-edit-decisions.json');}
async function init(){try{const r=await fetch('content.json');if(!r.ok)throw new Error('Content');state.data=await r.json();for(const kind of [...new Set(state.data.items.map(i=>i.kind))]){const o=el('option',kind);o.value=kind;$('kind').append(o);}for(const f of state.data.formats){const o=el('option',f.title);o.value=f.id;$('format').append(o);}$('format').value='short';$('format').onchange=formatChanged;for(const id of ['dialogue-language','seed','duration'])$(id).oninput=invalidate;$('search').oninput=collection;for(const id of ['kind','era','language-filter'])$(id).onchange=collection;$('reset').onclick=()=>{$('search').value='';for(const id of ['kind','era','language-filter'])$(id).value='all';collection();};$('plan').onclick=plan;$('download-plan').onclick=()=>{if(state.plan)save(state.plan,'vyomaraj-film-production-plan.json');};for(const a of state.data.agents){const c=el('article',undefined,'agent');c.append(el('span',a.slot+' · PROPOSAL','slot'),el('h3',a.proposed_label),el('p','Canonical name UNKNOWN · existing slot','small'));$('agents').append(c);}for(const s of state.data.sources){const li=el('li');sources([s.id],li);li.append(el('p',s.review_basis,'small'));$('sources').append(li);}state.data.backlog.forEach(x=>$('backlog').append(el('li',x)));
 $('permission').onchange=()=>{if(!$('permission').checked)clear();$('files').disabled=!$('permission').checked;cutButtons();};$('files').onchange=addFiles;$('clear').onclick=clear;$('stop-mix').onclick=()=>{stop();$('media-status').textContent='Preview stopped.';};$('play-mix').onclick=()=>{stop();if(validCuts())playAt(0,state.playToken);};$('export-edl').onclick=exportEDL;$('preview').ontimeupdate=()=>{const c=state.cuts[state.active];if(c&&!$('preview').seeking&&$('preview').currentTime>=c.out-0.025)nextCut();};$('preview').onended=()=>{if($('preview').ended)nextCut();};$('preview').onerror=()=>{if($('preview').getAttribute('src')){stop();$('media-status').textContent='Video playback failed. Try a supported codec. No file was uploaded.';}};window.addEventListener('pagehide',clear);collection();renderCuts();try{const response=await fetch('/api/status');const c=await response.json();state.ready=response.ok&&c.status==='local_preview_planning_only'&&c.experiences.includes('film');}catch(e){state.ready=false;}$('runtime').textContent=state.ready?'Local film routing and Vyomaraj/Jarvis handoff available. Rendering and streaming providers: not connected.':'Planning endpoint unavailable; discovery and local previews remain separate.';invalidate();}catch(e){$('error').hidden=false;}}
init();
