#!/usr/bin/env python3
"""Render only explicitly allowlisted sanitized handover reports; never serve repository paths."""
import argparse
import html
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
import re
from urllib.parse import urlsplit

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
HANDOVER_NOTE = 'NEXT_SESSION_HANDOVER_2026_10_04.txt'
RECOVERY_DOC = 'RECOVERY_AND_HANDOVER_PACKAGE_2026_10_04.md'
DR_SYNC_REPORT = 'DR_SYNC_RESULTS_2026_10_04.md'
TRANSFER_ZIP = 'transfer/NEXT_SESSION_TRANSFER_2026_10_04.zip'
POST_PR25_NOTE = 'NEXT_SESSION_HANDOVER_POST_PR25_2026_10_04.txt'
POST_PR25_ZIP = 'transfer/NEXT_SESSION_UPDATE_POST_PR25_2026_10_04.zip'
REPORTS = {
    '/sovereign/': 'SOVEREIGN_POLICY_2026_10_03.md',
    '/contracts/': 'ENTERTAINMENT_CONTRACTS_2026_10_03.md',
    '/reports/policy': 'VIEW_ONLY_UPDATE_2026_10_03.md',
    '/reports/aghor': 'AGHOR_RESEARCH_2026_10_03.md',
    '/reports/resilience': 'DR_AGHOR_INTEGRATION_2026_10_03.md',
    '/reports/agents': 'AGENT_RECONCILIATION_2026_10_03.md',
    '/reports/history': 'HISTORICAL_SYSTEM_INVENTORY_2026_10_03.md',
    '/': 'FULL_SYSTEM_INVENTORY_2026_10_03.md',
    '/dr-status': 'DR_RESOLUTION_2026_10_03.md',
    '/reports/research': 'RESEARCH_INTEGRATION_2026_10_03.md',
    '/reports/contents': 'EXPERIENCE_CONTENTS_2026_10_03.md',
    '/reports/film': 'FILM_THEATRE_ADS_UPDATE_2026_10_03.md',
    '/reports/music': 'MUSIC_AUDIO_VIDEO_UPDATE_2026_10_03.md',
    '/reports/bhakti': 'BHAKTI_FEATURE_UPDATE_2026_10_03.md',
    '/handover': 'HANDOVER_ALL_UPDATES_2026_10_03.txt',
    '/reports/next-session': HANDOVER_NOTE,
    '/reports/handover-notepad': HANDOVER_NOTE,
    '/reports/recovery': RECOVERY_DOC,
    '/reports/dr-sync': DR_SYNC_REPORT,
    '/reports/post-pr25-handover': POST_PR25_NOTE,
    '/reports/architecture': 'ARCHITECTURE_V16_8_2026_10_04.md',
    '/reports/build': 'BUILD_AND_CONFIGURATION_2026_10_04.md',
    '/reports/test-evidence': 'TEST_EVIDENCE_2026_10_04.json',
    '/reports/auto-align': 'AUTO_ALIGN_NEXT_SESSION_2026_10_04.md',
    '/reports/platform-check': 'PLATFORM_CONFIGURATION_CHECK_2026_10_04.md',
    '/reports/issues': 'ISSUES_AND_PRS_LEDGER_2026_10_04.md',
    '/reports/go-live': 'NAVARATRI_GO_LIVE_PLAN_2026_10_11.md',
    '/reports/stack': 'STACK_AND_PLATFORM_RECORD_2026_10_06.md',
}
# Canonical documents whose checked-in copy deliberately lives outside this directory. Each entry
# is a literal path fixed in code; no request value is ever joined to the filesystem, so the
# exact-route allowlist stays exact.
REFERENCE_REPORTS = {
    '/reports/chats': ROOT / 'Vyomaraj-All-Chats-Database-One-Month.md',
    '/reports/issue-6': ROOT / 'ops/dr/ISSUE_6_RESOLUTION_2026_10_04.md',
    '/reports/live-wiring': HERE / 'LIVE_WIRING_STATE_2026_10_06.json',
}
# Fixed, code-composed notices. Report text itself is never turned into markup or a hyperlink.
PAGE_NOTES = {
    '/reports/chats': '<p class="notice"><strong>All-chats count notice:</strong> the source heading says '
                      '28 chats while the file contains 34 numbered entries. The file is served unchanged; '
                      'owner confirmation is required before changing either count.</p>',
    '/reports/issue-6': '<p class="notice"><strong>Issue #6 resolution statement</strong> — acceptance '
                        'criteria, the correctly blocked run it followed, and the addenda that cite '
                        'the live DR record.</p>',
    '/reports/test-evidence': '<p class="notice"><strong>Recorded test evidence</strong> — the counts '
                              'are those actually executed at the recorded time, not a standing '
                              'promise about later runs.</p>',
    '/reports/go-live': '<p class="notice"><strong>Navaratri go-live plan</strong> — the four-day '
                        'run-up to Ghatasthapana, Sunday 11 October 2026: day-by-day plan, the '
                        'owner decisions that block it, the gates, and the risks in the order they '
                        'can stop a launch.</p>',
    '/reports/stack': '<p class="notice"><strong>Stack and platform record</strong> — what the '
                      'product is actually built on, the whole one-month archive with hashes, and '
                      'which claims in the old market-ready README have nothing running behind '
                      'them. Read section 3 before repeating any figure from it.</p>',
    '/reports/live-wiring': '<p class="notice"><strong>Live wiring state</strong> — generated by '
                            'verify_live_wiring.py against the running stack: which routes answer, '
                            'which downloads are byte-identical, how each lane pack binds to the '
                            'current agent registry, and what is explicitly not verified.</p>',
    '/reports/post-pr25-handover': '<p class="notice"><strong>Post-PR25 companion</strong> — created on '
                                   '2026-10-06 after this file was found to be missing from the '
                                   'repository; it records checkpoint #20 and the two windows in which '
                                   'verify-or-sync did not execute. Read its section 0 before quoting '
                                   'any earlier claim about it.</p>',
}
# route -> (file relative to this directory, exact content type)
DOWNLOADS = {'/download/inventory.md': (REPORTS['/'], 'text/plain; charset=utf-8'),
             '/download/dr-status.md': (REPORTS['/dr-status'], 'text/plain; charset=utf-8'),
             '/download/handover.txt': (REPORTS['/handover'], 'text/plain; charset=utf-8'),
             '/reports/download/next-session.txt': (HANDOVER_NOTE, 'text/plain; charset=utf-8'),
             '/reports/download/handover-notepad.txt': (HANDOVER_NOTE, 'text/plain; charset=utf-8'),
             '/reports/download/transfer-package.zip': (TRANSFER_ZIP, 'application/zip'),
             '/reports/download/post-pr25-handover.txt': (POST_PR25_NOTE, 'text/plain; charset=utf-8'),
             '/reports/download/post-pr25-transfer.zip': (POST_PR25_ZIP, 'application/zip'),
             '/reports/download/auto-align.json': ('AUTO_ALIGN_NEXT_SESSION.json', 'application/json'),
             '/reports/download/platform-check.md': ('PLATFORM_CONFIGURATION_CHECK_2026_10_04.md', 'text/plain; charset=utf-8'),
             '/reports/download/issues-ledger.json': ('ISSUES_AND_PRS_LEDGER.json', 'application/json')}
# Literal, code-composed links only: no report text is ever turned into a hyperlink.
RECOVERY_LINKS = ('<div class="notice"><strong>New-session runbook (in order):</strong> '
                  '<a href="/reports/issues">Issues and PRs ledger</a> &middot; '
                  '<a href="/reports/auto-align">Auto-align execution plan</a> &middot; '
                  '<a href="/reports/platform-check">Platform completion paths</a> &middot; '
                  '<a href="/reports/next-session">Next session handover</a> &middot; '
                  '<a href="/reports/download/next-session.txt">Download Notepad .txt</a> &middot; '
                  '<a href="/reports/dr-sync">DR sync results</a> &middot; '
                  '<a href="/reports/download/transfer-package.zip">Download transfer package .zip</a> &middot; '
                  '<a href="/reports/post-pr25-handover">Post-PR25 companion</a> &middot; '
                  '<a href="/reports/download/post-pr25-transfer.zip">Download post-PR25 package .zip</a></div>')
STYLE = '''body{margin:0;background:#0a1628;color:#e9eff7;font:16px/1.65 system-ui,sans-serif}
main{max-width:1100px;margin:32px auto;padding:32px;background:#0e2138;border:1px solid #23405f;border-radius:16px}
nav{display:flex;gap:18px;flex-wrap:wrap;padding:14px 0;border-bottom:1px solid #23405f}
a{color:#f5c96b}a:hover{color:#ffe0a3}h1,h2,h3{line-height:1.25;color:#f59e0b}h2{margin-top:48px;border-top:1px solid #23405f;padding-top:24px}
code{font-size:.88em;background:#132b47;color:#ffe0a3;padding:2px 4px;overflow-wrap:anywhere;border-radius:4px}
pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#081524;border:1px solid #23405f;border-radius:10px;padding:14px}
.table{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{border:1px solid #23405f;padding:10px;text-align:left;vertical-align:top}th{background:#16334f;color:#f5c96b}tr:nth-child(even) td{background:#0c1c2f}
.notice{background:#2a2109;padding:14px;border-left:4px solid #f59e0b;border-radius:6px}li{margin:5px 0}@media(max-width:700px){main{margin:0;padding:18px;border-radius:0}}'''
# The palette above is the Vyomaraj product palette (Shani Blue #0a1628, Kuber Gold #f59e0b).
# It is defined once here; every page of both report servers inherits it from this constant.



def inline(text):
    # Escape first; deliberately do not enable raw HTML or arbitrary hyperlinks.
    escaped = html.escape(text)
    escaped = re.sub(r'`([^`]+)`', r'<code>\1</code>', escaped)
    return re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', escaped)


def markdown(text):
    result, table, listing = [], False, False
    for line in text.splitlines():
        is_table = line.startswith('|') and line.endswith('|')
        is_list = line.startswith('- ')
        if table and not is_table:
            result.append('</tbody></table></div>'); table = False
        if listing and not is_list:
            result.append('</ul>'); listing = False
        if is_table:
            cells = re.split(r'(?<!\\)\|', line[1:-1])
            if all(re.fullmatch(r'\s*:?-+:?\s*', x) for x in cells):
                continue
            if not table:
                result.append('<div class="table"><table><tbody>')
                tag = 'th'; table = True
            else:
                tag = 'td'
            result.append('<tr>' + ''.join(f'<{tag}>{inline(x.strip().replace(chr(92)+"|", "|"))}</{tag}>' for x in cells) + '</tr>')
        elif is_list:
            if not listing:
                result.append('<ul>'); listing = True
            result.append('<li>' + inline(line[2:]) + '</li>')
        elif line.startswith('#'):
            match = re.match(r'^(#{1,6}) (.*)$', line)
            if match:
                n = len(match[1]); result.append(f'<h{n}>{inline(match[2])}</h{n}>')
            else:
                result.append('<p>' + inline(line) + '</p>')
        elif line.strip():
            result.append('<p>' + inline(line) + '</p>')
    if table: result.append('</tbody></table></div>')
    if listing: result.append('</ul>')
    return '\n'.join(result)


def render_document(path):
    """Render one allowlisted document to an HTML body. Non-markdown suffixes stay escaped text."""
    text = path.read_text(encoding='utf-8')
    if path.suffix == '.md':
        return markdown(text)
    if path.suffix == '.json':
        return ('<p class="notice">Machine-readable evidence, served exactly as recorded in the '
                'repository.</p><pre>' + html.escape(text) + '</pre>')
    return '<pre>' + html.escape(text) + '</pre>'


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        route = urlsplit(self.path).path
        filename = REPORTS.get(route) or (DOWNLOADS.get(route) or (None,))[0]
        if filename is None and route not in REFERENCE_REPORTS:
            self.send_error(404, 'Only the allowlisted reports are available'); return
        path = REFERENCE_REPORTS[route] if route in REFERENCE_REPORTS else HERE / filename
        if not path.is_file():
            self.send_error(404, 'Report not available'); return
        if route in DOWNLOADS:
            content = path.read_bytes()
            kind = DOWNLOADS[route][1]
        else:
            body = PAGE_NOTES.get(route, '') + render_document(path)
            if route == '/reports/history':
                body = '<p class="notice"><strong>HISTORICAL SNAPSHOT — NOT CURRENT.</strong> Current total: 128 counted slots and six uncounted headings. See the current inventory and agent reconciliation.</p>' + body
            if route == '/reports/recovery':
                body = RECOVERY_LINKS + body
            content = ('<!doctype html><html lang="en"><meta charset="utf-8">'
                       '<meta name="viewport" content="width=device-width,initial-scale=1">'
                       '<meta name="theme-color" content="#0a1628">'
                       '<title>Vyomaraj — verified reports</title><style>' + STYLE + '</style><main>'
                       '<nav aria-label="Viewer sections"><a href="/sovereign/">Sovereign</a><a href="/contracts/">Contracts</a><a href="/reports/policy">Latest policy update</a><a href="/">Current inventory</a><a href="/reports/resilience">Latest DR & integration</a><a href="/reports/aghor">Aghor research</a><a href="/reports/agents">Agent reconciliation</a><a href="/reports/history">Historical audit</a><a href="/dr-status">DR resolution</a>'
                       '<a href="/reports/research">Integrated research update</a><a href="/reports/contents">All experience contents</a><a href="/reports/film">Film</a><a href="/reports/music">Music</a><a href="/reports/bhakti">Bhakti</a><a href="/handover">Handover</a><a href="/comics/">Comics</a><a href="/approvals/">Owner approvals</a><a href="/finance/">Finance desk</a><a href="/upgrades/">Change desk</a><a href="/reports/architecture">Architecture</a><a href="/reports/build">Build &amp; configuration</a><a href="/reports/next-session">Next session handover</a><a href="/reports/handover-notepad">Handover notepad</a><a href="/reports/dr-sync">DR sync results</a><a href="/reports/post-pr25-handover">Post-PR25 companion</a><a href="/reports/recovery">Recovery package</a><a href="/reports/chats">All chats</a><a href="/reports/issue-6">Issue #6 resolution</a><a href="/reports/test-evidence">Test evidence</a><a href="/reports/auto-align">Auto-align plan</a><a href="/reports/platform-check">Platform check</a><a href="/reports/issues">New-session runbook (in order)</a><a href="/download/inventory.md">Download inventory</a></nav>'
                       '<p class="notice">Sanitized source inventory. Unknown names and unverified live services '
                       'are not presented as working integrations. Git snapshot match evidence is in the DR report; runtime/site disaster recovery remains unverified.</p>'
                       + body + '</main></html>').encode()
            kind = 'text/html; charset=utf-8'
        self.send_response(200)
        self.send_header('Content-Type', kind)
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('Cache-Control', 'no-store')
        self.send_header('Content-Security-Policy', "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'")
        if route in DOWNLOADS:
            self.send_header('Content-Disposition', f'attachment; filename="{Path(filename).name}"')
        self.send_header('Content-Length', str(len(content)))
        self.end_headers()
        self.wfile.write(content)

    def log_message(self, *args):
        pass  # Do not record user URLs, headers or query values.


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--port', type=int, default=4174)
    args = parser.parse_args()
    print(f'Report viewer listening on 0.0.0.0:{args.port}', flush=True)
    ThreadingHTTPServer(('0.0.0.0', args.port), Handler).serve_forever()
